const calculateSimilarity = (words1: string[], words2: string[]) => {
  const intersection = words1.filter(word => words2.includes(word))
  const union = [...new Set([...words1, ...words2])]
  return intersection.length / union.length
}

export const getDensity = (target: string) => {
  const targetWords = target.toLowerCase().split(/\W+/).filter(Boolean)

  let bestMatch = ''
  let maxSimilarity = -1
  for (const item of foodDensities) {
    const itemWords = item.name.toLowerCase().split(/\W+/).filter(Boolean)

    const similarity = calculateSimilarity(targetWords, itemWords)
    if (similarity > maxSimilarity) {
      maxSimilarity = similarity
      bestMatch = item
    }
  }
  return bestMatch
}

const foodDensities = [
  { name: 'agave syrup', density: 337.2, unit: 'ml' },
  { name: 'all-purpose flour', density: 120.5, unit: 'g' },
  { name: 'almond flour', density: 96.5, unit: 'g' },
  { name: 'apple juice concentrate', density: 280.9, unit: 'ml' },
  { name: 'apple', density: 113.5, unit: 'g' },
  { name: 'applesauce', density: 255.5, unit: 'g' },
  { name: 'castor sugar', density: 190.8, unit: 'g' },
  { name: 'baking powder', density: 192.7, unit: 'g' },
  { name: 'baking soda', density: 289.3, unit: 'g' },
  { name: 'banana', density: 227.6, unit: 'g' },
  { name: 'bread crumbs', density: 112.6, unit: 'g' },
  { name: 'panko bread crumbs', density: 50.2, unit: 'g' },
  { name: 'bread flour', density: 120.5, unit: 'g' },
  { name: 'brown rice flour', density: 128.6, unit: 'g' },
  { name: 'brown sugar', density: 213.5, unit: 'g' },
  { name: 'butter', density: 226.7, unit: 'g' },
  { name: 'buttermilk', density: 227.6, unit: 'ml' },
  { name: 'caramel', density: 284.6, unit: 'g' },
  { name: 'feta cheese', density: 114.5, unit: 'g' },
  { name: 'parmesan', density: 100.4, unit: 'g' },
  { name: 'ricotta', density: 227.6, unit: 'g' },
  { name: 'cheese', density: 113.5, unit: 'g' },
  { name: 'chocolate chips', density: 170.7, unit: 'g' },
  { name: 'chocolate chunks', density: 170.7, unit: 'g' },
  { name: 'chocolate', density: 170.7, unit: 'g' },
  { name: 'cocoa', density: 84.4, unit: 'g' },
  { name: 'toasted coconut', density: 85.2, unit: 'g' },
  { name: 'desiccated coconut', density: 85.2, unit: 'g' },
  { name: 'coconut flakes', density: 60.5, unit: 'g' },
  { name: 'shredded coconut', density: 53.2, unit: 'g' },
  { name: 'coconut cream', density: 285.3, unit: 'ml' },
  { name: 'coconut flour', density: 128.6, unit: 'g' },
  { name: 'coconut milk; canned, well shaken', density: 241.2, unit: 'ml' },
  { name: 'coconut milk, evaporated', density: 242.2, unit: 'ml' },
  { name: 'coconut milk powder', density: 114.5, unit: 'g' },
  { name: 'coconut oil', density: 226.7, unit: 'g' },
  { name: 'coconut sugar', density: 154.2, unit: 'g' },
  { name: 'powdered sugar', density: 113.8, unit: 'g' },
  { name: 'popcorn', density: 5.3, unit: 'g' },
  { name: 'corn syrup', density: 313.3, unit: 'ml' },
  { name: 'cornmeal', density: 156.8, unit: 'g' },
  { name: 'cornstarch', density: 112.6, unit: 'g' },
  { name: 'corn', density: 152.8, unit: 'g' },
  { name: 'heavy cream', density: 227.6, unit: 'ml' },
  { name: 'light cream', density: 227.6, unit: 'ml' },
  { name: 'cream', density: 227.6, unit: 'ml' },
  { name: 'half & half', density: 227.6, unit: 'ml' },
  { name: 'cream cheese', density: 227.6, unit: 'g' },
  { name: 'durum flour', density: 124.5, unit: 'g' },
  { name: 'egg', density: 233.1, unit: 'g' },
  { name: 'egg white', density: 223.6, unit: 'g' },
  { name: 'egg white powder', density: 176.5, unit: 'g' },
  { name: 'egg yolk', density: 274.0, unit: 'g' },
  { name: 'espresso powder', density: 112.6, unit: 'g' },
  { name: 'everything bagel topping', density: 140.9, unit: 'g' },
  { name: 'flax meal', density: 100.4, unit: 'g' },
  { name: 'flaxseed', density: 140.9, unit: 'g' },
  { name: 'ghee', density: 176.5, unit: 'g' },
  { name: 'rice flour', density: 120.9, unit: 'g' },
  { name: 'honey', density: 337.2, unit: 'ml' },
  { name: 'jam', density: 340.8, unit: 'ml' },
  { name: 'lard', density: 226.7, unit: 'g' },
  { name: 'lemon juice', density: 224.0, unit: 'ml' },
  { name: 'malt syrup', density: 345.1, unit: 'ml' },
  { name: 'malted milk powder', density: 141.4, unit: 'g' },
  { name: 'malted wheat flakes', density: 128.6, unit: 'g' },
  { name: 'maple sugar', density: 157.0, unit: 'g' },
  { name: 'maple syrup', density: 313.3, unit: 'ml' },
  { name: 'marshmallow spread', density: 124.0, unit: 'g' },
  { name: 'marshmallow fluff', density: 128.6, unit: 'g' },
  { name: 'marshmallow', density: 43.3, unit: 'g' },
  { name: 'marzipan', density: 291.1, unit: 'g' },
  { name: 'mascarpone cheese', density: 227.6, unit: 'g' },
  { name: 'mashed potatoes', density: 213.5, unit: 'g' },
  { name: 'mashed sweet potatoes', density: 240.3, unit: 'g' },
  { name: 'mayonnaise', density: 226.7, unit: 'g' },
  { name: 'medium rye flour', density: 106.7, unit: 'g' },
  { name: 'meringue powder', density: 172.2, unit: 'g' },
  { name: 'milk', density: 227.6, unit: 'ml' },
  { name: 'molasses', density: 341.2, unit: 'ml' },
  { name: 'oat flour', density: 92.4, unit: 'g' },
  { name: 'oats', density: 89.6, unit: 'g' },
  { name: 'olive oil', density: 200.8, unit: 'g' },
  { name: 'onion', density: 142.4, unit: 'g' },
  { name: 'palm shortening', density: 180.9, unit: 'g' },
  { name: 'peanut butter', density: 270.1, unit: 'g' },
  { name: 'peanut', density: 142.4, unit: 'g' },
  { name: 'pear', density: 163.6, unit: 'g' },
  { name: 'pecan', density: 114.5, unit: 'g' },
  { name: 'pine nut', density: 142.4, unit: 'g' },
  { name: 'pistachio', density: 120.9, unit: 'g' },
  { name: 'pizza sauce', density: 228.0, unit: 'g' },
  { name: 'polenta', density: 163.6, unit: 'g' },
  { name: 'poppy seed', density: 144.5, unit: 'g' },
  { name: 'potato flour', density: 184.8, unit: 'g' },
  { name: 'potato starch', density: 152.8, unit: 'g' },
  { name: 'pumpernickel flour', density: 106.7, unit: 'g' },
  { name: 'pumpkin puree', density: 227.6, unit: 'g' },
  { name: 'quinoa', density: 177.8, unit: 'g' },
  { name: 'raisin', density: 170.7, unit: 'g' },
  { name: 'raspberry', density: 120.9, unit: 'g' },
  { name: 'rhubarb', density: 120.9, unit: 'g' },
  { name: 'rice', density: 198.4, unit: 'g' },
  { name: 'rice flour', density: 142.4, unit: 'g' },
  { name: 'rice krispies', density: 28.2, unit: 'g' },
  { name: 'kosher salt', density: 257.0, unit: 'g' },
  { name: 'salt', density: 289.9, unit: 'g' },
  { name: 'self-rising flour', density: 113.5, unit: 'g' },
  { name: 'semolina flour', density: 163.6, unit: 'g' },
  { name: 'sesame seed', density: 142.4, unit: 'g' },
  { name: 'shallot', density: 157.0, unit: 'g' },
  { name: 'sorghum flour', density: 138.5, unit: 'g' },
  { name: 'sour cream', density: 227.6, unit: 'ml' },
  { name: 'soy flour', density: 141.4, unit: 'g' },
  { name: 'sparkling sugar', density: 228.0, unit: 'g' },
  { name: 'spelt flour', density: 99.9, unit: 'g' },
  { name: 'sprouted wheat flour', density: 113.5, unit: 'g' },
  { name: 'strawberry', density: 167.0, unit: 'g' },
  { name: 'sugar', density: 201.0, unit: 'g' },
  { name: 'splenda', density: 25.2, unit: 'g' },
  { name: 'sundried tomato', density: 170.7, unit: 'g' },
  { name: 'sunflower seed', density: 141.4, unit: 'g' },
  { name: 'sweetened condensed coconut milk', density: 289.9, unit: 'ml' },
  { name: 'sweetened condensed milk', density: 313.3, unit: 'ml' },
  { name: 'tahini paste', density: 257.0, unit: 'g' },
  { name: 'tapioca starch', density: 113.5, unit: 'g' },
  { name: 'tapioca', density: 168.1, unit: 'g' },
  { name: 'toasted almond flour', density: 96.5, unit: 'g' },
  { name: 'tomato paste', density: 232.1, unit: 'g' },
  { name: 'turbinado', density: 180.9, unit: 'g' },
  { name: 'vanilla extract', density: 224.0, unit: 'ml' },
  { name: 'vegetable oil', density: 199.2, unit: 'g' },
  { name: 'vegetable shortening', density: 184.8, unit: 'g' },
  { name: 'vital wheat gluten', density: 144.5, unit: 'g' },
  { name: 'walnut', density: 128.6, unit: 'g' },
  { name: 'water', density: 240.0, unit: 'ml' },
  { name: 'wheat bran', density: 64.1, unit: 'g' },
  { name: 'wheat germ', density: 112.6, unit: 'g' },
  { name: 'white chocolate chips', density: 170.7, unit: 'g' },
  { name: 'white rye flour', density: 106.7, unit: 'g' },
  { name: 'white whole wheat flour', density: 113.5, unit: 'g' },
  { name: 'whole grain flour blend', density: 113.5, unit: 'g' },
  { name: 'whole wheat flour, premium 100%', density: 113.5, unit: 'g' },
  { name: 'whole wheat pastry flour / graham flour', density: 96.5, unit: 'g' },
  { name: 'yeast', density: 144.5, unit: 'g' },
  { name: 'yogurt', density: 227.6, unit: 'ml' },
  { name: "Alcoholic beverage, beer", density: 236.0, unit: "ml" },
  { name: "Alcoholic beverage, distilled, all (gin, rum, vodka, whiskey)", density: 222.4, unit: "ml" },
  { name: "Alcoholic beverage, rice (sake)", density: 232.8, unit: "ml" },
  { name: "Alcoholic beverage, wine", density: 236.0, unit: "ml" },
  { name: "Dry white wine", density: 236.0, unit: "ml" },
  { name: "Alcoholic beverage, wine, cooking", density: 232.0, unit: "ml" },
  { name: "Alfalfa seeds, sprouted, raw", density: 33.0, unit: "g" },
  { name: "Almond paste, packed", density: 259.0, unit: "g" },
  { name: "Amaranth grain, cooked", density: 246.0, unit: "g" },
  { name: "Animal fat, bacon grease", density: 206.4, unit: "g" },
  { name: "Apple butter", density: 282.0, unit: "g" },
  { name: "Apple juice", density: 248.0, unit: "ml" },
  { name: "Applesauce, canned, sweetened", density: 255.0, unit: "g" },
  { name: "Applesauce, canned, unsweetened", density: 244.0, unit: "g" },
  { name: "Apricots, dehydrated", density: 119.0, unit: "g" },
  { name: "Apricots, frozen, sweetened", density: 242.0, unit: "g" },
  { name: "Artichokes, frozen, cooked", density: 168.0, unit: "g" },
  { name: "Arugula, raw", density: 20.0, unit: "g" },
  { name: "Asparagus, canned", density: 242.0, unit: "g" },
  { name: "Asparagus, cooked", density: 180.0, unit: "g" },
  { name: "Asparagus, raw", density: 134.0, unit: "g" },
  { name: "Bacon bits, meatless", density: 112.0, unit: "g" },
  { name: "Bacon, meatless", density: 144.0, unit: "g" },
  { name: "Baking powder", density: 190.0, unit: "g" },
  { name: "Baking soda", density: 240.0, unit: "g" },
  { name: "Banana, mashed", density: 227.0, unit: "g" },
  { name: "Bananas, dehydrated, or banana powder", density: 100.0, unit: "g" },
  { name: "Barley, hulled", density: 184.0, unit: "g" },
  { name: "Barley, pearled, cooked", density: 157.0, unit: "g" },
  { name: "Barley, pearled, raw", density: 200.0, unit: "g" },
  { name: "Beans, adzuki, cooked, boiled", density: 230.0, unit: "g" },
  { name: "Beans, adzuki, raw", density: 197.0, unit: "g" },
  { name: "Beans, baked, canned", density: 253.0, unit: "g" },
  { name: "Beans, baked, home prepared", density: 253.0, unit: "g" },
  { name: "Beans, black turtle, canned", density: 240.0, unit: "g" },
  { name: "Beans, black turtle, cooked, boiled", density: 185.0, unit: "g" },
  { name: "Beans, black turtle, raw", density: 184.0, unit: "g" },
  { name: "Beans, black, canned", density: 240.0, unit: "g" },
  { name: "Beans, black, cooked, boiled", density: 172.0, unit: "g" },
  { name: "Beans, black, raw", density: 194.0, unit: "g" },
  { name: "Beans, fava, in pod, raw", density: 126.0, unit: "g" },
  { name: "Beans, french, cooked, boiled", density: 177.0, unit: "g" },
  { name: "Beans, french, raw", density: 184.0, unit: "g" },
  { name: "Beans, kidney, canned", density: 256.0, unit: "g" },
  { name: "Beans, kidney, cooked, boiled", density: 177.0, unit: "g" },
  { name: "Beans, kidney, raw", density: 184.0, unit: "g" },
  { name: "Beans, mung, sprouted, canned", density: 125.0, unit: "g" },
  { name: "Beans, navy, canned", density: 262.0, unit: "g" },
  { name: "Beans, navy, cooked, boiled", density: 182.0, unit: "g" },
  { name: "Beans, navy, raw", density: 208.0, unit: "g" },
  { name: "Beans, navy, sprouted, raw", density: 104.0, unit: "g" },
  { name: "Beans, pinto, canned", density: 169.0, unit: "g" },
  { name: "Beans, pinto, cooked, boiled", density: 171.0, unit: "g" },
  { name: "Beans, pinto, raw", density: 193.0, unit: "g" },
  { name: "Beans, white, canned", density: 262.0, unit: "g" },
  { name: "Beans, white, cooked, boiled", density: 179.0, unit: "g" },
  { name: "Beans, white, raw", density: 202.0, unit: "g" },
  { name: "Beet greens, raw", density: 38.0, unit: "g" },
  { name: "Beverages, almond milk", density: 240.0, unit: "ml" },
  { name: "Blackberries, raw", density: 144.0, unit: "g" },
  { name: "Blueberries, dried, sweetened", density: 160.0, unit: "g" },
  { name: "Blueberries, raw", density: 148.0, unit: "g" },
  { name: "Bread crumbs, Japanese Panko", density: 50.0, unit: "g" },
  { name: "Bread crumbs, dry, grated, plain", density: 108.0, unit: "g" },
  { name: "Bread crumbs, dry, grated, seasoned", density: 120.0, unit: "g" },
  { name: "Breadfruit, raw", density: 220.0, unit: "g" },
  { name: "Broccoli, frozen, chopped, cooked, boiled", density: 184.0, unit: "g" },
  { name: "Brussels sprouts, cooked", density: 156.0, unit: "g" },
  { name: "Brussels sprouts, raw", density: 88.0, unit: "g" },
  { name: "Buckwheat groats, roasted, cooked", density: 168.0, unit: "g" },
  { name: "Buckwheat groats, roasted, dry", density: 164.0, unit: "g" },
  { name: "Buckwheat", density: 170.0, unit: "g" },
  { name: "Bulgur, cooked", density: 182.0, unit: "g" },
  { name: "Bulgur, dry", density: 140.0, unit: "g" },
  { name: "Butter oil", density: 205.0, unit: "g" },
  { name: "Butter", density: 230.0, unit: "g" },
  { name: "Butter, whipped", density: 151.0, unit: "g" },
  { name: "Candies, milk chocolate coated peanuts", density: 149.0, unit: "g" },
  { name: "Candies, milk chocolate coated raisins", density: 180.0, unit: "g" },
  { name: "Carrot juice, canned", density: 236.0, unit: "ml" },
  { name: "Carrot, dehydrated", density: 74.0, unit: "g" },
  { name: "Carrots, cooked", density: 155.2, unit: "g" },
  { name: "Carrots, diced", density: 142.0, unit: "g" },
  { name: "Carrots, chopped", density: 122.0, unit: "g" },
  { name: "Carrots, grated", density: 99.0, unit: "g" },
  { name: "Cassava, raw", density: 206.0, unit: "g" },
  { name: "Cauliflower, green, raw", density: 64.0, unit: "g" },
  { name: "Celeriac, raw", density: 156.0, unit: "g" },
  { name: "Celery, diced", density: 142.0, unit: "g" },
  { name: "Celery, raw", density: 120.0, unit: "g" },
  { name: "Cereal, Crispy Rice, Rice Krispies", density: 28.0, unit: "g" },
  { name: "Cereal, corn flakes", density: 25.0, unit: "g" },
  { name: "Cereal, corn grits, white, regular and quick, cooked", density: 257.0, unit: "g" },
  { name: "Cereal, corn grits, white, regular and quick, dry", density: 156.0, unit: "g" },
  { name: "Cereal, corn grits, yellow, regular and quick, cooked", density: 233.0, unit: "g" },
  { name: "Cereal, corn grits, yellow, regular and quick, dry", density: 156.0, unit: "g" },
  { name: "Cereal, farina, cooked", density: 240.0, unit: "g" },
  { name: "Cereal, farina, dry", density: 176.0, unit: "g" },
  { name: "Cereal, granola, homemade", density: 122.0, unit: "g" },
  { name: "Cereal, oats, instant, prepared", density: 240.0, unit: "g" },
  { name: "Cereal, rice, puffed", density: 14.0, unit: "g" },
  { name: "Cereal, wheat germ, toasted, plain", density: 113.0, unit: "g" },
  { name: "Cereal, wheat, puffed", density: 12.0, unit: "g" },
  { name: "Chard, swiss, raw", density: 36.0, unit: "g" },
  { name: "Cheese, american cheddar", density: 224.0, unit: "g" },
  { name: "Cheese, camembert", density: 246.0, unit: "g" },
  { name: "Cheese, cheddar, mozzarella, grated", density: 113.0, unit: "g" },
  { name: "Cheese, cottage", density: 227.0, unit: "g" },
  { name: "Cheese, cream", density: 232.0, unit: "g" },
  { name: "Cheese, cream, fat free", density: 288.0, unit: "g" },
  { name: "Cheese, cream, low fat", density: 240.0, unit: "g" },
  { name: "Cheese, feta", density: 113.0, unit: "g" },
  { name: "Cheese, limburger", density: 134.0, unit: "g" },
  { name: "Cheese, parmesan, grated", density: 100.0, unit: "g" },
  { name: "Cheese, parmesan, shredded", density: 80.0, unit: "g" },
  { name: "Cheese, ricotta", density: 248.0, unit: "g" },
  { name: "Chickpeas (garbanzo beans), canned, solids and liquids", density: 240.0, unit: "ml" },
  { name: "Chickpeas (garbanzo beans), cooked, boiled", density: 164.0, unit: "g" },
  { name: "Chickpeas (garbanzo beans), raw", density: 200.0, unit: "g" },
  { name: "Chicory, witloof, raw", density: 90.0, unit: "g" },
  { name: "Chocolate chips", density: 180.0, unit: "g" },
  { name: "Chocolate syrup", density: 300.0, unit: "g" },
  { name: "Cocoa, dry powder, unsweetened", density: 100.0, unit: "g" },
  { name: "Coconut cream, canned, sweetened", density: 296.0, unit: "g" },
  { name: "Coconut cream, raw", density: 240.0, unit: "g" },
  { name: "Coconut milk, canned", density: 226.0, unit: "g" },
  { name: "Coconut milk, frozen", density: 240.0, unit: "g" },
  { name: "Coconut milk, raw", density: 240.0, unit: "g" },
  { name: "Coconut water", density: 240.0, unit: "ml" },
  { name: "Coconut, sweetened, flakes", density: 85.0, unit: "g" },
  { name: "Coconut, unsweetened, grated", density: 113.0, unit: "g" },
  { name: "Coffee, brewed", density: 236.8, unit: "ml" },
  { name: "Coffee, instant, regular, powder", density: 48.0, unit: "g" },
  { name: "Coriander (cilantro) leaves, raw", density: 16.0, unit: "g" },
  { name: "Corn bran, crude", density: 76.0, unit: "g" },
  { name: "Corn, canned, cream style", density: 256.0, unit: "g" },
  { name: "Corn, canned, whole kernel, drained solids", density: 164.0, unit: "g" },
  { name: "Corn, canned, whole kernel, solids and liquids", density: 256.0, unit: "g" },
  { name: "Corn, cooked", density: 149.0, unit: "g" },
  { name: "Corn, kernels, boiled, drained", density: 165.0, unit: "g" },
  { name: "Corn, kernels, frozen", density: 136.0, unit: "g" },
  { name: "Corn, raw", density: 145.0, unit: "g" },
  { name: "Corn, white or yellow", density: 166.0, unit: "g" },
  { name: "Cornmeal, degermed", density: 157.0, unit: "g" },
  { name: "Cornmeal, whole-grain", density: 168.0, unit: "g" },
  { name: "Cornstarch", density: 128.0, unit: "g" },
  { name: "Couscous, dry", density: 173.0, unit: "g" },
  { name: "Cracker meal", density: 115.0, unit: "g" },
  { name: "Cranberries, dried, sweetened", density: 121.2, unit: "g" },
  { name: "Cranberry juice, unsweetened", density: 253.0, unit: "ml" },
  { name: "Cranberry sauce, canned, sweetened", density: 277.0, unit: "g" },
  { name: "Cream of tartar", density: 144.0, unit: "g" },
  { name: "Cream substitute, liquid", density: 242.0, unit: "g" },
  { name: "Cream substitute, powdered", density: 94.0, unit: "g" },
  { name: "Cream, half and half", density: 242.0, unit: "g" },
  { name: "Cream, half and half, fat free", density: 224.0, unit: "g" },
  { name: "Cream, heavy whipping", density: 240.0, unit: "g" },
  { name: "Cream, light (coffee cream or table cream)", density: 240.0, unit: "g" },
  { name: "Cream, light whipping", density: 240.0, unit: "g" },
  { name: "Cream, whipped, cream topping, pressurized", density: 60.0, unit: "g" },
  { name: "Cress, garden, cooked", density: 135.0, unit: "g" },
  { name: "Cress, garden, raw", density: 50.0, unit: "g" },
  { name: "Croutons, plain", density: 30.0, unit: "g" },
  { name: "Croutons, seasoned", density: 40.0, unit: "g" },
  { name: "Currants, raw", density: 112.0, unit: "g" },
  { name: "Dessert topping, pressurized", density: 70.0, unit: "g" },
  { name: "Dessert topping, semi solid, frozen", density: 75.0, unit: "g" },
  { name: "Dulce de Leche", density: 304.0, unit: "g" },
  { name: "Edamame, frozen, prepared", density: 155.0, unit: "g" },
  { name: "Edamame, frozen, unprepared", density: 118.0, unit: "g" },
  { name: "Egg substitute, liquid or frozen", density: 240.0, unit: "ml" },
  { name: "Egg", density: 243.0, unit: "g" },
  { name: "Egg, white, raw, fresh", density: 243.0, unit: "g" },
  { name: "Egg, yolk, raw, fresh", density: 243.0, unit: "g" },
  { name: "Eggnog", density: 254.0, unit: "g" },
  { name: "Elderberries, raw", density: 145.0, unit: "g" },
  { name: "Fat, beef tallow", density: 205.0, unit: "g" },
  { name: "Fat, chicken", density: 205.0, unit: "g" },
  { name: "Fat, duck", density: 205.0, unit: "g" },
  { name: "Fat, goose", density: 205.0, unit: "g" },
  { name: "Fat, mutton tallow", density: 205.0, unit: "g" },
  { name: "Fat, turkey", density: 205.0, unit: "g" },
  { name: "Figs, dried, uncooked", density: 149.0, unit: "g" },
  { name: "Fish broth", density: 244.0, unit: "g" },
  { name: "Flax meal", density: 100.0, unit: "g" },
  { name: "Flaxseed", density: 140.0, unit: "g" },
  {name: "Flour, all-purpose", density: 140.0, unit: "g"},
  {name: "Flour, all-purpose, sifted", density: 115.0, unit: "g"},
  {name: "Flour, almond", density: 96.0, unit: "g"},
  {name: "Flour, arrowroot", density: 128.0, unit: "g"},
  {name: "Flour, barley malt", density: 162.0, unit: "g"},
  {name: "Flour, barley or meal", density: 148.0, unit: "g"},
  {name: "Flour, bread", density: 157.0, unit: "g"},
  {name: "Flour, buckwheat, whole-groat", density: 120.0, unit: "g"},
  {name: "Flour, cake", density: 130.0, unit: "g"},
  {name: "Flour, carob", density: 103.0, unit: "g"},
  {name: "Flour, corn, degermed, yellow", density: 126.0, unit: "g"},
  {name: "Flour, corn, masa, white", density: 114.0, unit: "g"},
  {name: "Flour, corn, masa, yellow", density: 114.0, unit: "g"},
  {name: "Flour, corn, whole-grain, blue (harina de maiz morado)", density: 110.4, unit: "g"},
  {name: "Flour, corn, whole-grain, white", density: 117.0, unit: "g"},
  {name: "Flour, corn, whole-grain, yellow", density: 117.0, unit: "g"},
  {name: "Flour, gluten-free", density: 156.0, unit: "g"},
  {name: "Flour, millet", density: 119.0, unit: "g"},
  {name: "Flour, oat", density: 104.0, unit: "g"},
  {name: "Flour, pastry", density: 113.0, unit: "g"},
  {name: "Flour, peanut", density: 60.0, unit: "g"},
  {name: "Flour, potato", density: 160.0, unit: "g"},
  {name: "Flour, rice", density: 158.0, unit: "g"},
  {name: "Flour, rye, dark", density: 128.0, unit: "g"},
  {name: "Flour, rye, light", density: 102.0, unit: "g"},
  {name: "Flour, rye, medium", density: 102.0, unit: "g"},
  {name: "Flour, self-rising", density: 113.0, unit: "g"},
  {name: "Flour, sorghum", density: 121.0, unit: "g"},
  {name: "Flour, soy, defatted", density: 105.0, unit: "g"},
  {name: "Flour, soy, full-fat, raw", density: 83.2, unit: "g"},
  {name: "Flour, soy, low-fat", density: 88.0, unit: "g"},
  {name: "Flour, triticale, whole-grain", density: 130.0, unit: "g"},
  {name: "Flour, whole wheat", density: 140.0, unit: "g"},
  {name: "Flour, whole-grain", density: 120.0, unit: "g"},
  {name: "Frozen yogurt", density: 174.0, unit: "g"},
  {name: "Garlic, raw", density: 136.0, unit: "g"},
  {name: "Ginger root, raw", density: 96.0, unit: "g"},
  {name: "Graham cracker crumbs, boxed", density: 99.0, unit: "g"},
  {name: "Graham crackers, crushed", density: 142.0, unit: "g"},
  {name: "Honey", density: 339.0, unit: "g"},
  {name: "Hummus", density: 246.0, unit: "g"},
  {name: "Ice cream", density: 148.0, unit: "g"},
  {name: "Ice cream, soft serve", density: 172.0, unit: "g"},
  {name: "Jam, jelly and preserves", density: 320.0, unit: "g"},
  {name: "Ketchup", density: 240.0, unit: "g"},
  {name: "Lard", density: 205.0, unit: "g"},
  {name: "Lemon juice", density: 244.0, unit: "g"},
  {name: "Lemon peel, raw", density: 96.0, unit: "g"},
  {name: "Lentils, cooked, boiled", density: 198.0, unit: "g"},
  {name: "Lentils, raw", density: 192.0, unit: "g"},
  {name: "Lentils, sprouted, raw", density: 77.0, unit: "g"},
  {name: "Lima beans, canned, solids and liquids", density: 248.0, unit: "g"},
  {name: "Lima beans, cooked", density: 170.0, unit: "g"},
  {name: "Lima beans, raw", density: 156.0, unit: "g"},
  {name: "Lime juice", density: 242.0, unit: "g"},
  {name: "Litchis, raw", density: 190.0, unit: "g"},
  {name: "Margarine", density: 224.0, unit: "g"},
  {name: "Marmalade, orange", density: 320.0, unit: "g"},
  {name: "Marshmallow creme", density: 85.0, unit: "g"},
  {name: "Marshmallow fluff", density: 128.0, unit: "g"},
  {name: "Marshmallows, mini", density: 43.0, unit: "g"},
  {name: "Mayonnaise", density: 224.0, unit: "g"},
  {name: "Meringue powder", density: 172.0, unit: "g"},
  {name: "Milk", density: 227.0, unit: "ml"},
  {name: "Whole milk", density: 240.0, unit: "ml"},
  {name: "Milk, buttermilk", density: 255.0, unit: "g"},
  {name: "Milk, buttermilk, dried", density: 120.0, unit: "g"},
  {name: "Milk, canned, condensed, sweetened", density: 306.0, unit: "g"},
  {name: "Milk, canned, evaporated", density: 252.0, unit: "g"},
  {name: "Milk, chocolate", density: 250.0, unit: "g"},
  {name: "Milk, dry, nonfat, instant", density: 68.0, unit: "g"},
  {name: "Milk, dry, nonfat, regular", density: 120.0, unit: "g"},
  {name: "Milk, dry, whole", density: 128.0, unit: "g"},
  {name: "Millet, cooked", density: 174.0, unit: "g"},
  {name: "Millet, puffed", density: 21.0, unit: "g"},
  {name: "Millet, raw", density: 200.0, unit: "g"},
  {name: "Miso", density: 275.0, unit: "g"},
  {name: "Molasses", density: 337.0, unit: "g"},
  {name: "Mulberries, raw", density: 140.0, unit: "g"},
  {name: "Mung beans, cooked, boiled", density: 202.0, unit: "g"},
  {name: "Mung beans, raw", density: 207.0, unit: "g"},
  {name: "Mung beans, sprouted, cooked", density: 124.0, unit: "g"},
  {name: "Mung beans, sprouted, raw", density: 104.0, unit: "g"},
  {name: "Mushrooms, Chanterelle, raw", density: 54.0, unit: "g"},
  {name: "Mushrooms, canned, drained solids", density: 156.0, unit: "g"},
  {name: "Mushrooms, morel, raw", density: 66.0, unit: "g"},
  {name: "Mushrooms, straw, canned, drained solids", density: 182.0, unit: "g"},
  {name: "Mushrooms, white, cooked", density: 156.8, unit: "g"},
  {name: "Mustard, prepared, yellow", density: 249.0, unit: "g"},
  {name: "Natto", density: 175.0, unit: "g"},
  {name: "Noodles, egg, cooked", density: 160.0, unit: "g"},
  {name: "Noodles, egg, dry", density: 38.0, unit: "g"},
  {name: "Noodles, japanese, soba, cooked", density: 114.0, unit: "g"},
  {name: "Noodles, japanese, somen, cooked", density: 176.0, unit: "g"},
  {name: "Nuts, almonds, sliced", density: 86.0, unit: "g"},
  {name: "Nuts, almonds, slivered", density: 114.0, unit: "g"},
  {name: "Nuts, almonds, whole", density: 145.6, unit: "g"},
  {name: "Nuts, cashew, roasted", density: 137.6, unit: "g"},
  {name: "Nuts, chestnuts, raw, unpeeled", density: 145.0, unit: "g"},
  {name: "Nuts, chestnuts, roasted", density: 143.0, unit: "g"},
  {name: "Nuts, hazelnuts, whole", density: 142.0, unit: "g"},
  {name: "Nuts, macadamia, whole", density: 149.0, unit: "g"},
  {name: "Nuts, mixed nuts, dry roasted", density: 137.0, unit: "g"},
  {name: "Nuts, mixed nuts, oil roasted", density: 134.0, unit: "g"},
  {name: "Nuts, pecans, oil roasted", density: 110.0, unit: "g"},
  {name: "Nuts, pilinuts, dried", density: 120.0, unit: "g"},
  {name: "Nuts, pine nuts, dried", density: 135.0, unit: "g"},
  {name: "Nuts, pistachio nuts, dry roasted", density: 123.0, unit: "g"},
  {name: "Nuts, pistachio nuts, raw", density: 123.0, unit: "g"},
  {name: "Nuts, walnuts, chopped", density: 113.0, unit: "g"},
  {name: "Nuts, walnuts, whole", density: 124.8, unit: "g"},
  {name: "Oat bran, cooked", density: 219.0, unit: "g"},
  {name: "Oat bran, raw", density: 94.0, unit: "g"},
  {name: "Oats, quick cooking", density: 89.0, unit: "g"},
  {name: "Oats, steel cut, cooked", density: 255.0, unit: "g"},
  {name: "Oats, steel cut, raw", density: 198.0, unit: "g"},
  {name: "Oats, traditional rolled or thick flakes", density: 99.0, unit: "g"},
  {name: "Oil, almond", density: 218.0, unit: "g"},
  {name: "Oil, avocado", density: 218.0, unit: "g"},
  {name: "Oil, canola", density: 218.0, unit: "g"},
  {name: "Oil, cocoa butter", density: 218.0, unit: "g"},
  {name: "Oil, coconut", density: 218.0, unit: "g"},
  {name: "Oil, corn and canola", density: 224.0, unit: "g"},
  {name: "Oil, cottonseed", density: 218.0, unit: "g"},
  {name: "Oil, flaxseed", density: 218.0, unit: "g"},
  {name: "Oil, grapeseed", density: 218.0, unit: "g"},
  {name: "Oil, hazelnut", density: 218.0, unit: "g"},
  {name: "Oil, mustard", density: 218.0, unit: "g"},
  {name: "Oil, olive", density: 216.0, unit: "g"},
  {name: "Oil, palm", density: 216.0, unit: "g"},
  {name: "Oil, peanut", density: 216.0, unit: "g"},
  {name: "Oil, rice bran", density: 218.0, unit: "g"},
  {name: "Oil, safflower", density: 218.0, unit: "g"},
  {name: "Oil, sesame", density: 218.0, unit: "g"},
  {name: "Oil, soybean", density: 218.0, unit: "g"},
  {name: "Oil, sunflower", density: 218.0, unit: "g"},
  {name: "Oil, vegetable", density: 225.0, unit: "g"},
  { name: "Okra, raw", density: 100.0, unit: "g" },
  { name: "Orange juice", density: 249.0, unit: "ml" },
  { name: "Orange peel, raw", density: 96.0, unit: "g" },
  { name: "Oranges, raw, with peel", density: 170.0, unit: "g" },
  { name: "Parsley, fresh", density: 60.8, unit: "g" },
  { name: "Peanut butter", density: 270.0, unit: "g" },
  { name: "Peanuts, dry-roasted", density: 146.0, unit: "g" },
  { name: "Peanuts, raw", density: 146.0, unit: "g" },
  { name: "Peas, green, cooked", density: 160.0, unit: "g" },
  { name: "Peas, green, frozen, unprepared", density: 134.0, unit: "g" },
  { name: "Peas, green, raw", density: 145.0, unit: "g" },
  { name: "Peas, split, cooked, boiled", density: 196.0, unit: "g" },
  { name: "Peas, split, raw", density: 197.0, unit: "g" },
  { name: "Peas, sprouted, raw", density: 120.0, unit: "g" },
  { name: "Pepper, banana, raw", density: 124.0, unit: "g" },
  { name: "Peppermint, fresh", density: 25.6, unit: "g" },
  { name: "Pickle relish", density: 244.0, unit: "g" },
  { name: "Popcorn", density: 7.9, unit: "g" },
  { name: "Potatoes, baked", density: 122.0, unit: "g" },
  { name: "Potatoes, boiled, cooked", density: 156.0, unit: "g" },
  { name: "Potatoes, mashed", density: 210.0, unit: "g" },
  { name: "Prickly pears, raw", density: 149.0, unit: "g" },
  { name: "Prune juice, canned", density: 256.0, unit: "ml" },
  { name: "Prune puree", density: 288.0, unit: "g" },
  { name: "Puddings, dry mix, regular or instant, prepared", density: 280.0, unit: "g" },
  { name: "Pumpkin pie mix, canned", density: 270.0, unit: "g" },
  { name: "Pumpkin, canned", density: 245.0, unit: "g" },
  { name: "Purslane, cooked", density: 115.0, unit: "g" },
  { name: "Purslane, raw", density: 43.0, unit: "g" },
  { name: "Queso cotija", density: 96.0, unit: "g" },
  { name: "Quinoa, cooked", density: 185.0, unit: "g" },
  { name: "Quinoa, uncooked", density: 170.0, unit: "g" },
  { name: "Radish seeds, sprouted, raw", density: 38.0, unit: "g" },
  { name: "Raisins, loose", density: 140.0, unit: "g" },
  { name: "Raisins, packed", density: 170.0, unit: "g" },
  { name: "Raspberries, raw", density: 123.0, unit: "g" },
  { name: "Raspberries, wild (Northern Plains Indians)", density: 130.0, unit: "g" },
  { name: "Refried beans, canned", density: 238.0, unit: "g" },
  { name: "Rice bran, crude", density: 118.0, unit: "g" },
  { name: "Rice noodles, cooked", density: 176.0, unit: "g" },
  { name: "Rice, brown, long-grain, cooked", density: 195.0, unit: "g" },
  { name: "Rice, brown, long-grain, raw", density: 185.0, unit: "g" },
  { name: "Rice, brown, medium-grain, cooked", density: 195.0, unit: "g" },
  { name: "Rice, brown, medium-grain, raw", density: 190.0, unit: "g" },
  { name: "Rice, white, glutinous, cooked", density: 174.0, unit: "g" },
  { name: "Rice, white, glutinous, raw", density: 185.0, unit: "g" },
  { name: "Rice, white, long-grain, parboiled, cooked", density: 158.0, unit: "g" },
  { name: "Rice, white, long-grain, parboiled, dry", density: 185.0, unit: "g" },
  { name: "Rice, white, long-grain, regular, cooked", density: 158.0, unit: "g" },
  { name: "Rice, white, long-grain, regular, raw", density: 185.0, unit: "g" },
  { name: "Rice, white, medium-grain, cooked", density: 186.0, unit: "g" },
  { name: "Rice, white, medium-grain, raw", density: 195.0, unit: "g" },
  { name: "Rice, white, short-grain, cooked", density: 186.0, unit: "g" },
  { name: "Rice, white, short-grain, raw", density: 200.0, unit: "g" },
  { name: "Rose Hips, wild", density: 127.0, unit: "g" },
  { name: "Rosemary, fresh", density: 27.2, unit: "g" },
  { name: "Rowal, raw", density: 228.0, unit: "g" },
  { name: "Rye", density: 169.0, unit: "g" },
  { name: "Salt, course, Morton", density: 236.0, unit: "g" },
  { name: "Salt, Kosher, Diamond Crystal", density: 156.0, unit: "g" },
  { name: "Salt, Maldon", density: 135.0, unit: "g" },
  { name: "Salt, table", density: 292.0, unit: "g" },
  { name: "Sauce, barbecue", density: 286.0, unit: "g" },
  { name: "Sauce, cheese", density: 252.0, unit: "g" },
  { name: "Sauce, cocktail", density: 240.0, unit: "g" },
  { name: "Sauce, fish", density: 288.0, unit: "g" },
  { name: "Sauce, hoisin", density: 256.0, unit: "g" },
  { name: "Sauce, oyster", density: 288.0, unit: "g" },
  { name: "Sauce, pasta, spaghetti/marinara", density: 257.0, unit: "g" },
  { name: "Sauce, peanut", density: 288.0, unit: "g" },
  { name: "Sauce, pepper or hot", density: 225.6, unit: "g" },
  { name: "Sauce, pizza, canned", density: 252.0, unit: "g" },
  { name: "Sauce, plum", density: 305.0, unit: "g" },
  { name: "Sauce, salsa", density: 260.0, unit: "g" },
  { name: "Sauce, sofrito", density: 206.0, unit: "g" },
  { name: "Sauce, teriyaki", density: 288.0, unit: "g" },
  { name: "Sauce, worcestershire", density: 275.0, unit: "g" },
  { name: "Sauerkraut, canned", density: 142.0, unit: "g" },
  { name: "Seaweed, spirulina, dried", density: 112.0, unit: "g" },
  { name: "Seeds, pumpkin and squash seed kernels, dried", density: 129.0, unit: "g" },
  { name: "Seeds, pumpkin and squash seed kernels, roasted", density: 118.0, unit: "g" },
  { name: "Seeds, sesame butter, paste", density: 256.0, unit: "g" },
  { name: "Seeds, sesame butter, tahini", density: 240.0, unit: "g" },
  { name: "Seeds, sesame seeds, whole, dried", density: 144.0, unit: "g" },
  { name: "Seeds, sunflower seed kernels, dried", density: 140.0, unit: "g" },
  { name: "Seeds, sunflower seed kernels, dry roasted", density: 128.0, unit: "g" },
  { name: "Seeds, sunflower seed kernels, oil roasted", density: 135.0, unit: "g" },
  { name: "Semolina", density: 167.0, unit: "g" },
  { name: "Shortening, vegetable oil", density: 205.0, unit: "g" },
  { name: "Snacks, potato chips", density: 34.0, unit: "g" },
  { name: "Snacks, tortilla chips", density: 26.0, unit: "g" },
  { name: "Snacks, trail mix", density: 150.0, unit: "g" },
  { name: "Sorghum", density: 192.0, unit: "g" },
  { name: "Sour cream", density: 230.0, unit: "g" },
  { name: "Soy meal, defatted, raw", density: 122.0, unit: "g" },
  { name: "Soy sauce, made from hydrolyzed vegetable protein", density: 232.0, unit: "ml" },
  { name: "Soy sauce, made from soy (tamari)", density: 288.0, unit: "ml" },
  { name: "Soy sauce, made from soy and wheat (shoyu)", density: 255.0, unit: "ml" },
  { name: "Soybeans, cooked, boiled", density: 172.0, unit: "g" },
  { name: "Soybeans, dry roasted", density: 93.0, unit: "g" },
  { name: "Soybeans, raw", density: 186.0, unit: "g" },
  { name: "Soybeans, roasted", density: 172.0, unit: "g" },
  { name: "Soybeans, sprouted, cooked, steamed", density: 94.0, unit: "g" },
  { name: "Soybeans, sprouted, raw", density: 70.0, unit: "g" },
  { name: "Soymilk", density: 243.0, unit: "ml" },
  { name: "Spearmint, dried", density: 25.6, unit: "g" },
  { name: "Spearmint, fresh", density: 91.2, unit: "g" },
  { name: "Spelt, cooked", density: 194.0, unit: "g" },
  { name: "Spelt, uncooked", density: 174.0, unit: "g" },
  { name: "Spices, allspice, ground", density: 96.0, unit: "g" },
  { name: "Spices, caraway seed", density: 107.2, unit: "g" },
  { name: "Spices, celery seed", density: 104.0, unit: "g" },
  { name: "Spices, chervil, dried", density: 30.4, unit: "g" },
  { name: "Spices, chili powder", density: 128.0, unit: "g" },
  { name: "Spices, cinnamon, ground", density: 124.8, unit: "g" },
  { name: "Spices, cloves, ground", density: 104.0, unit: "g" },
  { name: "Spices, coriander leaf, dried", density: 28.8, unit: "g" },
  { name: "Spices, coriander seed", density: 80.0, unit: "g" },
  { name: "Spices, curry powder", density: 100.8, unit: "g" },
  { name: "Spices, dill seed", density: 105.6, unit: "g" },
  { name: "Spices, dill weed, dried", density: 49.6, unit: "g" },
  { name: "Spices, fenugreek seed", density: 177.6, unit: "g" },
  { name: "Spices, garlic powder", density: 155.2, unit: "g" },
  { name: "Spices, ginger, ground", density: 83.2, unit: "g" },
  { name: "Spices, mace, ground", density: 84.8, unit: "g" },
  { name: "Spices, marjoram, dried", density: 27.2, unit: "g" },
  { name: "Spices, mustard seed, ground", density: 100.8, unit: "g" },
  { name: "Spices, nutmeg, ground", density: 112.0, unit: "g" },
  { name: "Spices, onion powder", density: 110.4, unit: "g" },
  { name: "Spices, paprika", density: 108.8, unit: "g" },
  { name: "Spices, parsley, dried", density: 25.6, unit: "g" },
  { name: "Spices, pepper, red or cayenne", density: 84.8, unit: "g" },
  { name: "Spices, poppy seed", density: 140.8, unit: "g" },
  { name: "Spices, poultry seasoning", density: 70.4, unit: "g" },
  { name: "Spices, pumpkin pie spice", density: 89.6, unit: "g" },
  { name: "Spices, rosemary, dried", density: 52.8, unit: "g" },
  { name: "Spices, saffron", density: 33.6, unit: "g" },
  { name: "Spices, sage, ground", density: 32.0, unit: "g" },
  { name: "Spices, savory, ground", density: 70.4, unit: "g" },
  { name: "Spices, turmeric, ground", density: 150.4, unit: "g" },
  { name: "Spinach, canned, drained solids", density: 214.0, unit: "g" },
  { name: "Spinach, canned, solids and liquids", density: 234.0, unit: "g" },
  { name: "Spinach, cooked", density: 180.0, unit: "g" },
  { name: "Spinach, frozen, chopped or leaf, cooked", density: 190.0, unit: "g" },
  { name: "Spinach, frozen, chopped or leaf, unprepared", density: 156.0, unit: "g" },
  { name: "Spinach, raw", density: 30.0, unit: "g" },
  { name: "Sugar substitute, Splenda", density: 25.0, unit: "g" },
  { name: "Sugar, caster, superfine", density: 225.0, unit: "g" },
  { name: "Sugar, confectioner's, powdered, icing", density: 125.0, unit: "g" },
  { name: "Sugar, dark brown, packed", density: 239.0, unit: "g" },
  { name: "Sugar, demerara", density: 220.0, unit: "g" },
  { name: "Sugar, light brown, packed", density: 217.0, unit: "g" },
  { name: "Sugar, maple", density: 144.0, unit: "g" },
  { name: "Sugar, turbinado", density: 202.0, unit: "g" },
  { name: "Sugar, white, granulated", density: 220.0, unit: "g" },
  { name: "Sweetener, syrup, agave", density: 220.0, unit: "g" },
  { name: "Syrups, chocolate, fudge-type", density: 304.0, unit: "g" },
  { name: "Syrups, corn, dark", density: 328.0, unit: "g" },
  { name: "Syrups, corn, high-fructose", density: 310.0, unit: "g" },
  { name: "Syrups, corn, light", density: 341.0, unit: "g" },
  { name: "Syrups, grenadine", density: 320.0, unit: "g" },
  { name: "Syrups, malt", density: 332.0, unit: "g" },
  { name: "Syrups, maple", density: 315.0, unit: "g" },
  { name: "Syrups, sorghum", density: 330.0, unit: "g" },
  { name: "Tea, brewed", density: 236.8, unit: "ml" },
  { name: "Teff, cooked", density: 252.0, unit: "g" },
  { name: "Teff, uncooked", density: 193.0, unit: "g" },
  { name: "Tempeh", density: 166.0, unit: "g" },
  { name: "Thyme, fresh", density: 38.4, unit: "g" },
  { name: "Tofu", density: 252.0, unit: "g" },
  { name: "Tomato juice, canned", density: 243.0, unit: "ml" },
  { name: "Tomato products, canned, paste", density: 264.0, unit: "g" },
  { name: "Tomato products, canned, puree", density: 250.0, unit: "g" },
  { name: "Tomato sauce, canned", density: 245.0, unit: "g" },
  { name: "Tomatoes, crushed, canned", density: 242.0, unit: "g" },
  { name: "Tomatoes, sun-dried", density: 54.0, unit: "g" },
  { name: "Tomatoes, sun-dried, packed in oil", density: 110.0, unit: "g" },
  { name: "Toppings, butterscotch or caramel", density: 320.0, unit: "g" },
  { name: "Triticale", density: 192.0, unit: "g" },
  { name: "Vanilla extract", density: 208.0, unit: "ml" },
  { name: "Vinegar, balsamic", density: 255.0, unit: "ml" },
  { name: "Vinegar, cider", density: 239.0, unit: "ml" },
  { name: "Vinegar, distilled, white", density: 238.0, unit: "ml" },
  { name: "Vinegar, red wine", density: 239.0, unit: "ml" },
  { name: "Water", density: 236.8, unit: "ml" },
  { name: "Wheat bran, crude", density: 58.0, unit: "g" },
  { name: "Wheat germ, crude", density: 115.0, unit: "g" },
  { name: "Wheat, durum", density: 192.0, unit: "g" },
  { name: "Wheat, hard red or white", density: 192.0, unit: "g" },
  { name: "Wheat, soft red winter", density: 168.0, unit: "g" },
  { name: "Wheat, sprouted", density: 108.0, unit: "g" },
  { name: "Whey, acid, dried", density: 57.0, unit: "g" },
  { name: "Whey, acid, fluid", density: 246.0, unit: "ml" },
  { name: "Whey, sweet, dried", density: 145.0, unit: "g" },
  { name: "Whey, sweet, fluid", density: 246.0, unit: "ml" },
  { name: "Wild rice, cooked", density: 164.0, unit: "g" },
  { name: "Wild rice, raw", density: 160.0, unit: "g" },
  { name: "Yeast extract spread", density: 288.0, unit: "g" },
  { name: "Yeast, baker's, active dry", density: 172.8, unit: "g" },
  { name: "Yeast, nutritional", density: 100.0, unit: "g" },
  { name: "Yogurt", density: 227.0, unit: "g" },
  { name: "Zucchini, shredded", density: 156.0, unit: "g" }
]